projects:
  3things:
    schemaPath: src/graphql/schema.json
    includes:
      - graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: .
